apiVersion: v1
kind: Service
metadata:
  name: quality-app-service
  namespace: devops-project-ns
spec:
  selector:
    app: quality-app
  ports:
    - protocol: TCP
      port: 80       # Port the service listens on
      targetPort: 5000 # Port the app runs on inside the container
  type: NodePort     # Allows you to access it from your Windows browser